Fix membership nemesis crash
The membership nemesis would occassionally crash with the following:
```
WARN [2025-11-24 14:10:15,259] jepsen worker nemesis - jepsen.generator.interpreter Process :nemesis crashed
java.lang.ClassCastException: class clojure.lang.Keyword cannot be cast to class java.lang.CharSequence (clojure.lang.Keyword is in unnamed module of loader 'app'; java.lang.CharSequence is in module java.base of loader 'bootstrap')
	at clojure.core$re_matcher.invokeStatic(core.clj:4902)
	at clojure.core$re_find.invokeStatic(core.clj:4951)
	at clojure.core$re_find.invoke(core.clj:4951)
	at jepsen.nats.nemesis.MemberState.resolve_op(nemesis.clj:211)
```

Turned out to be the `op` reading `:removed`. Since we're simply looking for `did not receive a response` we can simply convert it to a string anyway.

Signed-off-by: Maurice van Veen <github@mauricevanveen.com>